### ISSUE TITLE
Get the next release out

### ISSUE THREAD

**Issue by matthiasbeyer** [neithernut/git-dit#107]
I'm not entirely sure what is left to do.

I would go on merge the PRs which are in the queue:

- [x] https://github.com/neithernut/git-dit/pull/101
- [x] https://github.com/neithernut/git-dit/pull/104
- [x] https://github.com/neithernut/git-dit/pull/105
- [x] https://github.com/neithernut/git-dit/pull/106
- [x] https://github.com/neithernut/git-dit/pull/109

After these are merged, we should smoke-test all the things and then get the release out.

---

I'm pretty sure that we can get out the release within the next two weeks, what do you think?

**Comment by matthiasbeyer** [comment]
Sidenote: As soon as this release is out, we should commit to a bit more stable API (not as in "we are 1.0-stable", but rather in "we should at least **consider** keeping backwards compatibility").

This would greatly help in developing applications based on the lib.

**Comment by neithernut** [comment]
That's one of the reason why we refactor now rather than after the release.
