### ISSUE TITLE
Workflow examples

### ISSUE THREAD

**Issue by matthiasbeyer** [neithernut/git-dit#111]
Someone on reddit said that we need workflow examples. Probably in the README file.

**Comment by neithernut** [comment]
Not sure.An additional md file would make sense. Or putting a few examples in the manpage.

**Comment by matthiasbeyer** [comment]
:+1: on examples in the manpage! I would use the manpage extensively and put all the things in there  (and I'd opt for one big manpage with several sections in favour of several manpages, but that's another topic)!
