### ISSUE TITLE
Please add your project to https://dist-bugs.branchable.com/

### ISSUE THREAD

**Issue by xtaran** [neithernut/git-dit#112]
Please add your project to the Distributed Bug Tracking Systems Wiki at https://dist-bugs.branchable.com/.

Maybe also announce it at https://kitenet.net/cgi-bin/mailman/listinfo/dist-bugs respectively dist-bugs@kitenet.net.

TIA!

**Comment by matthiasbeyer** [comment]
Note to self: Mailinglist-post is pending.

**Comment by matthiasbeyer** [comment]
Done.

**Comment by xtaran** [comment]
Arrived, thanks. :-)

**Comment by xtaran** [comment]
Here's the link to the mail in the list's archive: https://kitenet.net/pipermail/dist-bugs/2017-June/000098.html

**Comment by xtaran** [comment]
First reply already, but just to the list: https://kitenet.net/pipermail/dist-bugs/2017-June/000099.html

@matthiasbeyer: Are you subscribed to the list?

**Comment by matthiasbeyer** [comment]
yes, I am subscribed.
