### ISSUE TITLE
git-dit list/show panics

### ISSUE THREAD

**Issue by matthiasbeyer** [neithernut/git-dit#116]
```
$  ./target/debug/git-dit list
IO Error
No such file or directory (os error 2)
```

```
$ ./target/debug/git-dit show 47762849e251495d701112a8290f0ba56e433b78
IO Error
No such file or directory (os error 2)
```

can you reproduce?

**Comment by matthiasbeyer** [comment]
btw: Can reproduce on 0.2.0

**Comment by neithernut** [comment]
Could not reproduce. I tried rebuilding, but the build fails locally because of `unicode-bidi` using features which were unstable in rust-1.16. Looks like I have to update before retrying.

**Comment by neithernut** [comment]
Sidenote: this is actually a case of `unicode-bidi` not abiding semantic versioning, is it? Normally you'd have to make sure libraries compile with the same compiler version used when the library or module was released originally. I guess at least some parts of the Rust community don't give much of a thought about it. Sad thing is that we decided to do the same, simply because we didn't have a chance due to the dependency.

It also demonstrates some drawbacks of this kind of package-management: I see not sane possibility to mask the "faulty" version of `unicode-bidi`.

**Comment by neithernut** [comment]
Meh. According to my package-manager, 1.16.1 is the latest version of rust I can install right now...

**Comment by neithernut** [comment]
Sidenote: I guess I'll never be friends with the rust eco-system.

**Comment by neithernut** [comment]
I rebuild after forcing `cargo` to use an old version of `unicode-bidi`. Still can't reproduce.

**Comment by matthiasbeyer** [comment]
I can also not reproduce on a newly cloned repository on a Ubuntu 16.04 VM. But locally it fails, even after updating dependencies and such. I will investigate next week.

Sidenote: Are you trying to get me to delete your "Sidenote" comments because they do not belong here?

**Comment by neithernut** [comment]
I just assigned you since you appear to be the only one able to reproduce the issue.

**Comment by matthiasbeyer** [comment]
I just found out that, since I have an `alias less='less -R'` in my `.bashrc`, my `PAGER` variable is `less -R` (I just `grep`ed my system for `PAGER` and `less`, the former returning nothing, the latter the alias) which does not work well with the `::std::process::Command::new()` function, apparently.

We should handle this case somehow.

**Comment by neithernut** [comment]
I think the correct way of doing this is to invoke the shell and pass it the configuration string. Another option would be to split the thing via `String::split_whitespace`, create the command and append the arguments.

Are you doing this anytime soon or shall I provide a fix, @matthiasbeyer? You are the assignee and you already have a setup for reproduction.

**Comment by matthiasbeyer** [comment]
As I'm about to dive into my masters thesis, I'd apprechiate a fix from you. Also you know the codebase _much_ better than I do. If you have a hard time finding time, I can do this, though it might take a few days.

Do you plan a release within the next two weeks? If not, I think I will find a quiet minute to do this.

**Comment by neithernut** [comment]
Well, you're not the only one who's about to write a Thesis and there are still a view other things to be done (I wrote you a mail a few weeks ago). But I if you feel you can't spare the time, I'll fix the issue.

I'll publish a release within the next few weeks. Probably before Sep. 15.

**Comment by matthiasbeyer** [comment]
I'm on a hacking convention from Sept 15th to Sept 17th. Two options: Release before that date, so I can show off... or release after that date, so I can fix things. I'd go for the first option, though 15th will do fine.

**Comment by neithernut** [comment]
Ok, in this case I'll do another Sunday release on the 17th.
