### ISSUE TITLE
Flag to _not_ use pager

### ISSUE THREAD

**Issue by matthiasbeyer** [neithernut/git-dit#161]
A flag for _not_ piping to pager is missing.

Also: If the terminal is wide/high enough, we shouldn't pipe to the pager at all (or provide a flag to enforce it).

**Comment by matthiasbeyer** [comment]
Also, if `stdout` is not a tty, we shouldn't call the pager. Things like `git dit list | head` do not work.

**Comment by neithernut** [comment]
This is already handled by `git`. E.g. run `git --no-pager dit list`.
