### ISSUE TITLE
Helppage: new --metadata missing prefix description

### ISSUE THREAD

**Issue by asuivelentine** [neithernut/git-dit#168]
When creating a new issue, all metadata-keys are prefixed with `Dit-` this behaviour is not described in the helppage.

**Comment by matthiasbeyer** [comment]
In fact, the `Dit-` prefix is _not_ added. 

Also, the documentation that "these keys are available" is wrong. There's no checks in the codebase whether these keys are passed, they are forwarded to the issue as-is. So one should actually be able to pass any key-value pair.
