### ISSUE TITLE
Port check-message to rust

### ISSUE THREAD

**Issue by neithernut** [neithernut/git-dit#26]
What the title says.

**Comment by neithernut** [comment]
I'm not sure whether we need a corresponding function in the library or whether a function in the binary is sufficient. In the latter case, implementers should keep in mind that this functionality is also used in other functions.

If `git2::Repository::commit()` performs a check already (which I consider unlikely), we can also just drop the `check-message` command.

**Comment by matthiasbeyer** [comment]
:+1: on dropping.

**Comment by neithernut** [comment]
Blocks #37 and #38.

**Comment by neithernut** [comment]
It appears that we need this functionality at least internally.
