### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by neithernut** [neithernut/git-dit#78]
Up until now, we neglected automated testing. All we did was manually smoke-testing new functionality.
To reduce the probability of errors leaking through, we should definitely make use of automated testing, including tests using on-the-fly repos.
Obviously, the library and library-internal modules should be the primary target for testing. However, it was suggested having some smoke-tests on the binary, in order to prevent unintentionally breaking the user interface.

**Comment by neithernut** [comment]
I'm considering postponing test-writing until _after_ the refactoring that will be done following the next release. I don't think it makes much sense to write tests just to rewrite them completely a few days or weeks later. Any thoughts, @matthiasbeyer?

**Comment by matthiasbeyer** [comment]
I cannot participate in this until mid-september, so I removed the assignment.
