### ISSUE TITLE
Build and install man page

### ISSUE THREAD

**Issue by neithernut** [neithernut/git-dit#92]
There are two possible solutions:
 * make cargo build the existing man page (`git-dit.1.md`)
 * build a man page from the `clap` CLI spec

Blocks #93.

**Comment by neithernut** [comment]
I'd prefer keeping the `git-dit.1.md`. I doubt that we could have the separation of plumbing and porcelain commands in a generated man-page.

**Comment by matthiasbeyer** [comment]
We would have to wait for https://github.com/kbknapp/clap-rs/issues/552, but we could "work around" this by using the `git-dit.1.md` approach until this feature is implemented in clap.
